SJL/SJL/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('SJLApp.urls')),
    path('admin/', admin.site.urls),
]

SJL/SJLApp/urls.py
from django.urls import re_path
from . import views

app_name = 'SJLApp'

#Links view methods to urls
urlpatterns = [
    re_path(r'^$', views.index, name='home'),
    re_path(r'^about-us/$', views.about_us, name='about_us'),
    re_path(r'^index/$', views.index, name='index'),

    re_path(r'^shader/(?P<pk>\d+)/$', views.shader_detail, name='shader_detail_page'),

    re_path(r'^create-shader/$', views.create_shader, name='create_shader'),
    re_path(r'^update-shader/(?P<pk>\d+)/$', views.update_shader, name='update_shader'),
    re_path(r'^delete-shader/(?P<pk>\d+)/$', views.delete_shader, name='delete_shader'),

    re_path(r'^comment/(?P<pk>\d+)/$', views.create_comment, name='comment'),
    re_path(r'^delete-comment/(?P<pk>\d+)/$', views.delete_comment, name='delete_comment'),

    re_path(r'^user/$', views.user, name='user'),
    re_path(r'^user/(?P<pk>\d+)/$', views.any_user, name='user_detail_page'),

    re_path(r'^account/login-page/', views.user_login_page, name='login_page'),
    re_path(r'^account/login/$', views.user_login, name='login'),
    re_path(r'^account/logout/$', views.user_logout, name='logout'),
    re_path(r'^account/create-page/$', views.create_user_page, name='create_user_page'),
    re_path(r'^account/create/$', views.create_user, name='create_user'),
    re_path(r'^account/change-user-info/$', views.change_user_info, name='change_user_info'),
    re_path(r'^account/change-pass/$', views.change_password, name='change_pass'),
    re_path(r'account/change-about/$', views.change_about, name='change_about'),

    re_path(r'^api/shader/$', views.api_shaders, name='api_shaders'),
    re_path(r'^api/shader/(?P<pk>\d+)/$', views.api_shader, name='api_shader'),
    re_path(r'^api/user/(?P<pk>\d+)/$', views.api_user_shaders, name='api_user_shaders'),
]

handler404 = "SJLApp.views.error404"

SJL/SJLApp/models.py
from pickle import FALSE
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.dispatch import receiver

#Extending the base Django user model via a one to one relation
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    about = models.TextField(max_length=500, blank=True)

    #Extended fields/methods go here

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

def defaultConfig():
    return {
            "menu": {
                "controls": {
                "red": {
                    "max": 1,
                    "min": 0,
                    "type": "range"
                },
                "green": {
                    "max": 1,
                    "min": 0,
                    "type": "range"
                },
                "blue": {
                    "max": 1,
                    "min": 0,
                    "type": "range"
                }
                },
                "menuOrder": [
                "red",
                "green",
                "blue"
                ]
            },
            "settings": {
                "viewport": {
                "range": {
                    "x": 4,
                    "y": 4
                },
                "center": {
                    "x": 0,
                    "y": 0
                },
                "rotation": 0
                },
                "rangeSettings": {
                "red": {
                    "max": 1,
                    "min": 0,
                    "phase": 0,
                    "value": 0,
                    "animated": False,
                    "amplitude": 1,
                    "frequency": 0.2
                },
                "blue": {
                    "max": 1,
                    "min": 0,
                    "phase": 2,
                    "value": 0,
                    "animated": False,
                    "amplitude": 1,
                    "frequency": 0.2
                },
                "green": {
                    "max": 1,
                    "min": 0,
                    "phase": 4,
                    "value": 0,
                    "animated": False,
                    "amplitude": 1,
                    "frequency": 0.2
                }
                },
                "selectSettings": {}
            }
        }

defaultCode = "precision mediump float;\n\nuniform float GREEN;\nuniform float RED;\nuniform float BLUE;\n\nvoid main(){\n\tvec3 color = vec3(RED, BLUE, GREEN);\n\tgl_FragColor = vec4(color,1.0);\n}"

class Shader(models.Model):
    title = models.CharField(default='Default Title', max_length=64)
    description = models.TextField(default='Default Description', max_length=256)
    date = models.DateTimeField(auto_now_add=True)
    is_public = models.BooleanField(default=True)
    views = models.IntegerField(default=0)
    code = models.TextField(default=defaultCode, max_length=10000)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    config = models.JSONField(default=defaultConfig)

    def __str__(self):
        return self.title

class Comment(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    content = models.CharField(blank=True, max_length=256)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    shader = models.ForeignKey(Shader, on_delete=models.CASCADE)

SJL/SJLApp/forms/forms_shader.py
from django import forms
from SJLApp.models import Shader, Comment

class ShaderForm(forms.ModelForm):
    class Meta:
        model = Shader
        fields = ['title', 'description','code', 'is_public', 'config']
        widgets = {
            'title': forms.TextInput(attrs={
                'id': 'shader-title',
                'placeholder': 'Default Title', 
                'class': 'form-control',
            }),
            'description': forms.Textarea(attrs={
                'id': 'shader-description',
                'placeholder': 'Default Description', 
                'class': 'form-control',
                'type': 'textarea',
                'rows': '5',
                'style': 'height: 100%;'
            }),
            'is_public': forms.CheckboxInput(attrs={ 
                'id': 'shader-ispublic',
                'class': 'form-check-input btn-danger bg-danger border-danger',
                'type': 'checkbox',
            }),
            'code' : forms.Textarea(attrs={
                'id': 'shader-code',
                'hidden': 'hidden',
            }),
            'config' : forms.Textarea(attrs={
                'id': 'shader-config',
                'hidden': 'hidden',
            }),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={
                'placeholder': 'Default Comment', 
                'class': 'form-control',
            }),
        }

SJL/SJLApp/views/views_get.py
from django.db.models import Q
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.core.paginator import Paginator
from django.core.exceptions import FieldError
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.decorators.http import require_http_methods
from SJLApp.forms import *
from SJLApp.models import Shader

SHADER_INDEX_PAGE_SIZE = 9

def import_global_context():
    context = {}
    context['login_form'] = LoginForm()
    return context

def filter_by_query_parameters(queryset, querydict):
    q_object = None
    for key in querydict:
        if not q_object:
            q_object = Q(**{key: querydict.get(key)})
        q_object &= Q(**{key: querydict.get(key)})
    if q_object:
        return queryset.filter(q_object)
    else:
        return queryset

def error404(request, *args, **argv):
    return render(request, 'SJLApp/404.html', status=404)

@require_http_methods(["GET"])
def about_us(request):
    context = import_global_context()
    return render(request, 'SJLApp/aboutUs.html', context=context)

#Page for logged in user
@require_http_methods(["GET"])
def user(request):
    context = import_global_context()
    user = request.user
    if user.is_authenticated:
        for key in request.GET:
            context[key] = request.GET.get(key)
        context['this_user'] = user
        context['querystring'] = request.GET.urlencode()
        context['change_pass_form'] = ChangePasswordForm(user)
        context['change_user_info_form'] = ChangeUserInfoForm(instance=user)
        context['about_form'] = AboutForm(instance=user.profile)
        return render(request, 'SJLApp/user.html', context=context)
    else:
        return redirect(reverse_lazy("SJLApp:login_page"))

#Gets user by pk
@require_http_methods(["GET"])
def any_user(request, pk):
    context = import_global_context()
    if User.objects.filter(pk=pk).exists():
        user = User.objects.get(pk=pk)
        for key in request.GET:
            context[key] = request.GET.get(key)
        context['querystring'] = request.GET.urlencode()
        context['this_user'] = user
        if request.user == user:
            context['change_pass_form'] = ChangePasswordForm(user)
            context['change_user_info_form'] = ChangeUserInfoForm(instance=user)
            context['about_form'] = AboutForm(instance=user.profile)
        return render(request, 'SJLApp/user.html', context=context)
    elif request.user.is_authenticated:
        messages.error(request, "User not found")
        return redirect(reverse_lazy("SJLApp:user"))
    else:
        return error404(request)

# List of shaders
@require_http_methods(["GET"])
def index(request):
    context = import_global_context()
    for key in request.GET:
        context[key] = request.GET.get(key)
    context['querystring'] = request.GET.urlencode()
    return render(request, 'SJLApp/index.html', context=context)

# Specific view of shader
@require_http_methods(["GET"])
def shader_detail(request, pk):
    context = import_global_context()
    if Shader.objects.filter(pk=pk).exists():
        shader = Shader.objects.get(pk=pk)
        user = request.user
        if shader.is_public or user == shader.user:
            context['shader'] = shader
            context['shader_form'] = ShaderForm(instance=shader)
            context['comment_form'] = CommentForm()
            if(user == shader.user):
                return render(request, 'SJLApp/detailOwner.html', context=context)
            else:
                return render(request, 'SJLApp/detailViewer.html', context=context)
        else:
            messages.error(request, "Access Denied")
            return redirect(reverse_lazy("SJLApp:index"))
    else:
        messages.error(request, "Shader not found.")
        return redirect(reverse_lazy("SJLApp:index"))

@require_http_methods(["GET"])
def create_user_page(request):
    if request.user.is_authenticated:
        return redirect(reverse_lazy('SJLApp:user'))
    else:
        context = import_global_context()
        context['create_user_form'] = UserCreateForm()
        return render(request, 'SJLApp/createUser.html', context=context)

@require_http_methods(["GET"])
def user_login_page(request):
    if request.user.is_authenticated:
        messages.error(request, "Already logged in")
        return redirect(reverse_lazy("SJLApp:user"))
    else:
        context = import_global_context()
        context['login_form'] = LoginForm()
        return render(request, 'SJLApp/login.html', context=context)

@require_http_methods(["GET"])
def api_shaders(request):
    querydict = request.GET.copy()
    if 'page' in querydict:
        pg = querydict.pop('page')[0]
    else:
        pg = 1
    shaders = Shader.objects.filter(is_public=True).order_by('pk')
    try:
        shaders = filter_by_query_parameters(shaders, querydict)
    except FieldError:
        messages.error(request, "Invalid Request")
        return redirect(reverse_lazy("SJLApp:index"))
    paginator = Paginator(shaders, SHADER_INDEX_PAGE_SIZE)
    data = list()
    for shader in paginator.get_page(pg):
        dict = {
            'id': shader.pk,
            'name': shader.title,
            'code': shader.code,
            'config': shader.config,
        }
        data.append(dict)
    response = JsonResponse(data, safe=False)
    return response

@require_http_methods(["GET"])
def api_shader(request, pk):
    if Shader.objects.filter(pk=pk).exists():
        shader = Shader.objects.get(pk=pk)
        if shader.is_public or request.user == shader.user:
            data = []
            dict = {
                'id': shader.pk,
                'name': shader.title,
                'code': shader.code,
                'config': shader.config,
            }
            data.append(dict)
            response = JsonResponse(data, safe=False)
            return response
        else:
            messages.error(request, "Access denied")
            return redirect(reverse_lazy("SJLApp:login_page"))
    else:
        return error404(request)

@require_http_methods(["GET"])
def api_user_shaders(request, pk):
    if User.objects.filter(pk=pk).exists():
        querydict = request.GET.copy()
        if 'page' in querydict:
            pg = querydict.pop('page')[0]
        else:
            pg = 1
        user = User.objects.get(pk=pk)
        if request.user == user:
            shaders = Shader.objects.filter(user=user).order_by('pk')
        else:
            shaders = Shader.objects.filter(user=user, is_public=True).order_by('pk')
        try:
            shaders = filter_by_query_parameters(shaders, querydict)
        except FieldError:
            messages.error(request, "Invalid Request")
            return redirect(reverse_lazy("SJLApp:index"))
        paginator = Paginator(shaders, SHADER_INDEX_PAGE_SIZE)
        data = []
        for shader in paginator.get_page(pg):
            dict = {
                'id': shader.pk,
                'name': shader.title,
                'code': shader.code,
                'config': shader.config,
            }
            data.append(dict)
        response = JsonResponse(data, safe=False)
        return response
    else:
        return error404(request)

SJL/SJLApp/templates/SJLApp/base.html
{% load tags %}
{% load static %}

{% url 'SJLApp:index' as index %}
{% url 'SJLApp:about_us' as aboutUs %}
{% url 'SJLApp:user' as profile %}
{% url 'SJLApp:login' as login %}
{% url 'SJLApp:logout' as logout %}
{% url 'SJLApp:create_shader' as create_shader %}
{% url 'SJLApp:login_page' as login_page %}
{% url 'SJLApp:create_user_page' as create_user_page %}

<html>
    <head>
        <meta charset="UTF-8">
        <link rel="icon" href="{% static 'images/logo2IconOnly.png' %}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'my-codemirror/plugin/codemirror/lib/codemirror.css' %}">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        {% block head %}{% endblock head %}
        <style>
            .nav-link.text-danger.active {
                font-weight: bold;
            }
            .bg-julia {
                background-image: url("{% static 'images/julia-set.png' %}");
            }
        </style>
    </head>
    <body>
        <!-- Modal Error popup -->
        <div class="modal fade in" id="messageModal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Alert</h5>
                    </div>
                    <div class="modal-body">
                        {% for msg in messages %}
                            {{ msg }} <br>
                        {% endfor %}
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- Modal Error activation -->
        {% if messages %}
            <script type="text/javascript">
                $(document).ready(function(){
                    $("#messageModal").modal('show');
                });
            </script>
        {% endif %}
        <nav class="navbar navbar-light bg-white">
            <div class="container-fluid">
                <div>
                    <button class="navbar-toggler mx-3" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand justify-content-end mx-3" href="{{ index }}">
                        <img class="w3-round" src="{% static 'images/logo2TextOnly.png' %}" width="auto" height="40px"></img>
                    </a>
                </div>
                {% if user.is_authenticated %}
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-danger" href="#" id="signInDropdown" role="button" data-bs-toggle="dropdown">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <div class="m-2"><a class="text-danger" href="{{ profile }}">My Profile</a></div>
                            <hr class="my-2 text-dark">
                            <div class="m-2">
                                <form class="m-0" action="{{ create_shader }}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" type="submit">Create Shader</button>
                                </form>
                            </div>
                            <div class="m-2">
                                <form class="m-0" action="{{ logout }}" method="post">
                                    {% csrf_token %}
                                    <div class="input-group flex-nowrap">
                                        <button type="submit" class="btn btn-danger">Logout</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                {% else %}
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-danger" href="#" id="signInDropdown" role="button" data-bs-toggle="dropdown">
                            Sign In
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <form class="m-0" action="{{ login }}" method="post">
                                {% csrf_token %}
                                <div class="form-control border-0">{{ login_form.username }}</div>
                                <div class="form-control border-0">{{ login_form.password }}</div>
                                <div class="form-control border-0"><button type="submit" class="btn btn-danger">Login</button></div>
                                <div class="form-control border-0"><a class="text-danger" href="{{ create_user_page }}">Dont have an account?</a></div>
                            </form>
                        </div>
                    </div>
                {% endif %}
                <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
                    <div class="offcanvas-header pb-1">
                        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">
                            <a class="navbar-brand justify-content-end" href="{{ home }}">
                                <img class="w3-round" src="{% static 'images/logo2TextOnly.png' %}" width="200px" height="auto"></img>
                            </a>
                        </h5>
                        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
                    </div>
                    <div class="offcanvas-body">
                        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                            <hr class="my-0 text-dark">
                            <li class="nav-item">
                                <a class="nav-link {% active request index %} text-danger" href="{{ index }}">Index</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link {% active request aboutUs %} text-danger" href="{{ aboutUs }}">About Us</a>
                            </li>
                            <hr class="my-0 text-dark">
                            {% if user.is_authenticated %}
                                <li class="nav-item">
                                    <a class="nav-link text-danger" href="{{ profile }}">Profile</a>
                                </li>
                            {% else %}
                                <li class="nav-item">
                                    <a class="nav-link text-danger" href="{{ login_page }}">Log In</a>
                                </li>
                                <li>
                                    <a class="nav-link text-danger" href="{{ create_user_page }}">Create Account</a>
                                </li>
                            {% endif %}
                            <hr class="my-0 text-dark">
                            <li class="nav-item my-3">
                                <form action="{{ create_shader }}" method="POST">
                                    {% csrf_token %}
                                    <button class="btn btn-danger" type="submit">Create Shader</button>
                                </form>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
        {% block page %}{% endblock page %}
        <footer class="py-3 bg-white">
            <ul class="nav justify-content-center">
                <li class="nav-item"><a href="{{ index }}" class="nav-link px-2 text-danger {% active request index %}">Index</a></li>
                <li class="nav-item"><a href="{{ aboutUs }}" class="nav-link px-2 text-danger {% active request aboutUs %}">About Us</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link px-2 text-danger" href="{{ profile }}">Profile</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link px-2 text-danger" href="{{ login_page }}">Log In</a></li>
                    <li><a class="nav-link px-2 text-danger" href="{{ create_user_page }}">Create Account</a></li>
                {% endif %}
            </ul>
            <div class="d-flex justify-content-center"><hr class="my-2 text-dark w-50"></div>
            <p class="text-center text-danger">&copy; 2022 L14, Inc</p>
          </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    </body>
</html>

SJL/SJLApp/templates/SJLApp/detailViewer.html
{% extends "SJLApp/base.html" %}
{% load static %}

{% block head %}
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1">
    <title>SJL Shader - {{ shader.title }}</title>

    <link rel="stylesheet" href="{% static 'assets/fontello/css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'assets/SocialShareKit/css/social-share-kit.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/skeleton/normalize.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'detail-build/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <style>
        .slide-out-menu-right {
            right: -80%;
            position: absolute;
            height: 100%;
            width: 80%;
            background-color: white;
        }
        .menu-button-right {
            position: absolute;
            left: -20px;
            width: 20px;
            color: red;
            background-color: rgba(55, 55, 55, 0.7);
            text-align: center;
        }
        @media (min-width: 520px){
            .slide-out-menu-right {
                width: 500px;
                right: -500;
            }
        }
        .menu-open-right {
            right: 0;
        }
    </style>
{% endblock head %}

{% block page %}
    {% url 'SJLApp:api_shader' pk=shader.pk as api_shader %}
    {% url 'SJLApp:comment' pk=shader.pk as comment %}

    <menu class="slide-out-menu-right">
        <div class="menu-button-right">
            <button id="menu-button-right" class="menu-button-icon">
                <i class="bi bi-caret-left"></i>
            </button>
        </div>
        <div class="menu-scroll">
            <ul class="nav nav-tabs">
                <li class="nav-item" role="presentation">
                    <button class="nav-link active text-danger" data-bs-toggle="tab" data-bs-target="#info" type="button">Info</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link text-danger" data-bs-toggle="tab" data-bs-target="#glsl" type="button" onclick="refreshMyEditor()">GLSL Editor</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link text-danger" data-bs-toggle="tab" data-bs-target="#comments" type="button">Comments</button>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" style="height: calc(100vh - 95px);" id="info">
                    <h1 class="jumbotron-heading mx-3">{{ shader.title }}</h1>
                    <div class="m-3">
                        <img src = "{% static 'images/profile-blank.jpg' %}"
                            class="rounded-circle mx-1" width="30" height="30"/>
                            <a href="{% url 'SJLApp:user_detail_page' pk=shader.user.id %}">{{ shader.user.username }}</a>
                        <p class="m-1">{{ shader.date }}</p>
                        <p class="m-1">{{ shader.description }}</p>
                    </div>
                </div>
                <div class="tab-pane fade" id="glsl">
                    <div class="col" style = "max-width: 500px">
                        <!-- Getting the value of the shader code from the shader model. -->
                        <input type="hidden" name="shader-code" id="shader-code" value="{{shader.code}}">
        
                        <!-- The code editor's division! -->
                        <div class="editor-class" id="editor-id" style="height: calc(100vh - 97px);"></div>
                        
                        <!--Insert editor here!-->
                        <script type="text/javascript" src="{% static 'my-codemirror/plugin/codemirror/lib/codemirror.js' %}"></script>
                        <script type="text/javascript" src="{% static 'my-codemirror/plugin/codemirror/mode/glsl/glsl.js' %}"></script>
                        <!--Editor is a child division of the division with class "editor-class" and optionally can be restricted to the size of the div with id "editor-id".-->
                        <script type="text/javascript" src="{% static 'my-codemirror/js/default.js' %}"></script>
                    </div>
                </div>
                <div class="tab-pane fade" style="height: calc(100vh - 95px);" id="comments">
                    <div class="card" style="padding: 10px 10px 10px 10px">
                        <div class="card-text">
                            <p>Comments ({{ shader.comment_set.count }})</p>
                        </div>
                        
                        <form action="{{ comment }}" method="POST">
                            {% csrf_token %}
                            <div style="padding-top: 5px">
                                {{ comment_form.content }}
                                <button type="submit" class="btn btn-sm btn-outline-secondary mt-1"
                                        style="float:right">Submit
                                </button>
                            </div>
                        </form>
                        
                        {% for comment in shader.comment_set.all %}
                            <div class="card-body" style="background-color: lightgray;">
                                <img src = "{% static 'images/profile-blank.jpg' %}"
                                    class="rounded-circle" width="30" height="30"/> {{ comment.user.username }}
                                <p></p>
                                <p>{{ comment.content }}</p>
                                {% if user == comment.user %}
                                    <form action="{% url 'SJLApp:delete_comment' pk=comment.pk %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="comment_id" value="{{ comment.id }}"/>
                                        <button class="btn btn-primary" type="submit">Delete</button>
                                    </form>
                                {% endif %}
                            </div>
                        {% endfor %}
            
                    </div>
                </div>
            </div>
        </div>
    </menu>
    <input id="url" type="hidden" value="{{ api_shader }}"/>
    <main id="root">
        <section class="content">
            <section>
                <div>
                    <canvas id="main"></canvas>
                </div>
            </section>
        </section>
    </main>

    <script src="{% static 'detail-build/bundle.js' %}"></script>
    <script>
        /* eslint-disable */
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-83600496-1', 'auto');
        ga('send', 'pageview');
        /* eslint-enable */
    </script>
    <script>
        $("#menu-button-right").click(function(){
            var element = $(".slide-out-menu-right")[0];
            element.classList.toggle("menu-open-right");
        })
    </script>
    
{% endblock page %}